<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="7" hostname="Personal" failures="5" tests="9" name="CheckParallel" time="14.032" errors="0" timestamp="24 Sep 2018 15:22:23 GMT">
  <testcase classname="testSuite.E2E.TestFunctionalityA" name="test3" time="4.141">
    <failure type="java.lang.AssertionError" message="Supposed to be passed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Supposed to be passed expected [true] but found [false]
at testSuite.E2E.TestFunctionalityA.test3(TestFunctionalityA.java:38)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="testSuite.E2E.TestFunctionalityB" name="test5" time="0.734"/>
  <testcase classname="testSuite.E2E.TestFunctionalityB" name="test6" time="0.705">
    <failure type="java.lang.AssertionError" message="Supposed to be failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Supposed to be failed expected [true] but found [false]
at testSuite.E2E.TestFunctionalityB.test6(TestFunctionalityB.java:32)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test6 -->
  <testcase classname="testSuite.E2E.TestFunctionalityC" name="test7" time="0.002">
    <failure type="java.lang.AssertionError" message="Supposed to be failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Supposed to be failed expected [true] but found [false]
at testSuite.E2E.TestFunctionalityC.test7(TestFunctionalityC.java:29)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test7 -->
  <testcase classname="testSuite.E2E.TestFunctionalityC" name="test8" time="0.004">
    <failure type="java.lang.AssertionError" message="Supposed to be failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Supposed to be failed expected [true] but found [false]
at testSuite.E2E.TestFunctionalityC.test8(TestFunctionalityC.java:36)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test8 -->
  <testcase classname="testSuite.E2E.TestFunctionalityC" name="test9" time="0.004"/>
  <testcase classname="testSuite.E2E.TestFunctionalityA" name="test2" time="0.79"/>
  <testcase classname="testSuite.E2E.TestFunctionalityA" name="test1" time="3.067">
    <failure type="java.lang.AssertionError" message="Supposed to be failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Supposed to be failed expected [true] but found [false]
at testSuite.E2E.TestFunctionalityA.test1(TestFunctionalityA.java:16)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="testSuite.E2E.TestFunctionalityB" name="test4" time="0.974"/>
  <testcase classname="testSuite.E2E.TestFunctionalityC" name="@AfterTest afterTest" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest afterTest -->
  <testcase classname="testSuite.E2E.TestFunctionalityC" name="@BeforeTest beforeTest" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest beforeTest -->
  <testcase classname="easy.util.BaseUtils" name="@BeforeSuite beforeSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite beforeSuite -->
  <testcase classname="easy.util.BaseUtils" name="@BeforeSuite beforeSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite beforeSuite -->
  <testcase classname="easy.util.BaseUtils" name="@AfterTest afterTest" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest afterTest -->
  <testcase classname="easy.util.BaseUtils" name="@AfterTest afterTest" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest afterTest -->
  <testcase classname="easy.util.BaseUtils" name="@BeforeTest beforeTest" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest beforeTest -->
</testsuite> <!-- CheckParallel -->
